### ISSUE TITLE
Negative number for fp use

### ISSUE THREAD

**Issue by schoeke** [hannesm/jackline#106]
I encountered a strange bug, that I am not sure how to exactly replicate. A contact had a new OTR fp. It showed me a negative number of times the fp was used: 

```
***OTR key*** not verified key (used -1 times) (...)
```
I am not quite sure what kind of information could help finding out what is going on, so let me know if you need more info.

**Comment by hannesm** [comment]
could you tell me which revision you use? it says in your self-contact on startup `*** welcome to jackline XXXXXXX`

**Comment by hannesm** [comment]
(I thought I fixed it when it was reported #98)

**Comment by schoeke** [comment]
```*** welcome to jackline 4554c6f defaults in yes-no ***```

**Comment by hannesm** [comment]
sounds good... you could have gone to your self-contact and scrolled all the way up to the startup message :)
