### ISSUE TITLE
Notifications has confusing behaviour

### ISSUE THREAD

**Issue by infinity0** [hannesm/jackline#109]
Currently, notifications fire when:

- a message is received from a contact (all of whose previous messages I've seen)
- I select a contact whose has sent me some messages I haven't seen

Notifications are *not* fired when:

-  a message is received from a contact, where an older notification was already fired previously, and I haven't read that older message yet.

This is a bit unintuitive. Notifications should be fired *for each* message received, and not when I go to read that message.

It would also be good to detect if the current X window is not active, and send notifications in this case too (even if the contact is selected, which would normally suppress a notification).

**Comment by hannesm** [comment]
(sorry, in transit) -- the last point, doing sth with X - is what I will definitively not implement. what I personally use is a bell character, and the terminal sets the urgency flag on the window (thus, the window manager notifies this).

**Comment by infinity0** [comment]
OK, no worries about the X thing, I'm now using this instead: https://gist.github.com/infinity0/5d04337ef2457d31628d

Looks like it's fairly easy for `notification_callback` to distinguish between "new message" and "all messages read" because `notification.state` transitions between "connected_notifications" vs "connected". However, it would be nice if each new message fires `notification_callback` as well. (You could just re-write/touch `notification.state` with the same contents i.e. "connected_notifications", which would work with the above wrapper scripts too.)

**Comment by hannesm** [comment]
thanks for the report, I think I fixed this in 9d76f38...
