### ISSUE TITLE
Prefer forward-secret TLS

### ISSUE THREAD

**Issue by infinity0** [hannesm/jackline#112]
It seems that jackline does not use forward-secret TLS by default:

~~~~
| *** connecting *** to pwned.gg (37.59.43.183 on port 5222)
| *** TLS session info *** (TLS_1_2 TLS_RSA_WITH_AES_256_CBC_SHA256)
~~~~

but my server supports it:

~~~~
$ openssl s_client -starttls xmpp -connect pwned.gg:xmpp-client 
[..]
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
~~~~

(Not sure if this is more of an ocaml-tls issue)

**Comment by cfcs** [comment]
Perhaps time to implement https://github.com/hannesm/jackline/issues/3

That being said, `ocaml-tls` should probably prefer DHE-suites?

**Comment by hannesm** [comment]
OCaml-TLS always prefers DHE suites. as seen [here](https://github.com/mirleft/ocaml-tls/blob/master/lib/config.ml#L42-L57).  It does not (yet) support EC, though.

**Comment by hannesm** [comment]
in my opinion this is not an issue here: ECC might appear at some point; #3 tracks the TLS config exposure which might appear at another point... closing, please reopen if you disagree.
