### ISSUE TITLE
Presence on status line doesn't change

### ISSUE THREAD

**Issue by diethyl** [hannesm/jackline#113]
If the JID in the config file doesn't include a resource identifier, the status line's presence remains "Offline" and cannot change.

I can't take a deeper look right now, but I assume that the JID the server returns doesn't match the bare JID, so presence updates fail to occur.

**Comment by hannesm** [comment]
you should not have no resource in your config.  to debug it a bit more, you can pass `-d` to jackline, and it will write a `out.txt` in your working directory, in which it will dump the network communication.

**Comment by diethyl** [comment]
I used a JID like foo@bar.baz/ during the initial configuration, so everything worked correctly apart from the status line, which remained red and couldn't be updated even if I changed my status. It all works as expected if I follow the configuration prompt's format and include a resource identifier, but I thought I'd give you a heads up since it wasn't obvious what was causing this.

**Comment by hannesm** [comment]
Thanks. I guess I should forbid the empty resource identifier then :)
