### ISSUE TITLE
Dubious use of Ptime

### ISSUE THREAD

**Issue by dbuenzli** [hannesm/jackline#114]
[Here](https://github.com/hannesm/jackline/blob/26f87240afad85b4c31e9aae720074e7352ba417/src/xmpp_callbacks.ml#L194). 

Do you realize that you are computing local time here ? A quick look at the rest of the program [seems to indicate](https://github.com/hannesm/jackline/blob/a65025ff20ee7e35d11674ce8f2e266472603499/cli/cli_client.ml#L107) that timestamps arguments are in UTC in the program --- also I wonder why you are not simply using `Ptime.t` values, since it would make completely unambiguous what we are dealing with here.

Ptime is precisely designed so that you never need to perform such computation yourself and treat tz offsets only as a rendering issue. Values of type `Ptime.t` are always in UTC (because that's where posix time lies is by definition), this is documented in the description of the [type](http://erratique.ch/software/ptime/doc/Ptime.html#TYPEt) and it is even repeated in the documentation of [Ptime.of_rfc3339](http://erratique.ch/software/ptime/doc/Ptime.html#VALof_rfc3339) that the timestamp you get is in UTC.

Btw. I'm going to change the signature of `Ptime.of_rfc3339` to make it less ugly. So do pin ptime on 83cad3e95707da872a4b rather than on master until I make a release (which should happen in the following days).

**Comment by hannesm** [comment]
Thanks, well spotted.  I just (in 1b8bec2) got around to use `Ptime.t` instead of float, compute the timezone offset once at startup, and ignore the tz_offset from `of_rfc3339`.

Also thanks for the headsup regarding the upcoming API change.

**Comment by hannesm** [comment]
fixed, depends on ptime now (and now using Ptime.t / Ptime.date instead of float)
