### ISSUE TITLE
newer versions (since notty merge) breaks backspace and the terminal after jackline closes

### ISSUE THREAD

**Issue by infinity0** [hannesm/jackline#123]
The backspace key doesn't work when I run jackline now in xfce4-terminal. It does work when I run jackline via the linux console (ctrl-alt-f1). However, **in both cases** the terminal is broken after I exit jackline - I can't see the things I type, and when I enter `reset`, I see the output `Erase is �` and then I can see my input get echoed again but the backspace key is **still broken**.

I couldn't identify the exact commit that caused this, but 7f6de65 is good, then the next several commits fail to build, then d907088 is bad.

**Comment by infinity0** [comment]
Some more info: bug still exists even if i move `.profile .bashrc` somewhere else. Bug goes away if I run `zsh` via linux console, but bug remains if I run `zsh` via xfce4-terminal. Possibly something on my environment is causing this, will investigate further...

**Comment by infinity0** [comment]
Bug persists even if I change shell to dash `/bin/sh` or even `/bin/csh` and completely comment out `/etc/profile` so that it's blank. At this point the only envvars I have set are HOME HUSHLOGIN IFS LANG LANGUAGE LOGNAME MAIL OPTIND PATH PPID PS1 PS2 PS4 PWD SHELL TERM USER XDG_RUNTIME_DIR XDG_SEAT XDG_SESSION_COOKIE XDG_SESSION_ID XDG_VTNR _ so I don't see how any of the could be affecting this... As mentioned, the bug doesn't appear in a zsh login shell though, so perhaps it has a special workaround for this sort of thing...

**Comment by infinity0** [comment]
Confirmed fix works, thanks!

**Comment by hannesm** [comment]
thx; and thx for reporting!
