### ISSUE TITLE
Home / End keys no longer work

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#125]
Going to the beginning / end of a line using the Home / End keys does no longer work as it used to.
Ctrl-a and Ctrl-e still do, however, so perhaps this is the new tty library not implementing the same aliases?

**Comment by hannesm** [comment]
hmm, works here.. which terminal is that, and could you clone notty (from https://github.com/pqwy/notty), `./configure --enable-examples`; `make`, and run `./keys.native` and see whether home and end get reported

**Comment by cfcs** [comment]
This works for me, too. Not sure if due to an update or if I had something misconfigured before.
Closing the issue.
