### ISSUE TITLE
regression: C-<space> C-w C-y not implemented

### ISSUE THREAD

**Issue by hannesm** [hannesm/jackline#126]

**Comment by cfcs** [comment]
Ctrl-k works, but Ctrl-y doesn't. Slightly annoying.

**Comment by duckdalbe** [comment]
I'd be happy to have a working C-w for deleting the last word. Paste-buffer would be a surplus.

**Comment by hannesm** [comment]
@duckdalbe there you have your C-w, and @cfcs C-y is back as well... what is not there is C-SPACE (for mark, interoperating with C-w)....

**Comment by duckdalbe** [comment]
nice, thanks! :)
