### ISSUE TITLE
Make OTR warnings bold

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#142]
Would be nice if important stuff like the one below was bold:

```
***OTR key*** POSSIBLE BREAKIN ATTEMPT! new not verified key, but a verified is available verify /fingerprint [fp] over second channel
```

(If there are no objections I'll add that when I get around to it)

**Comment by sternenseemann** [comment]
I guess there are no objection :p

**Comment by hannesm** [comment]
this is now red
