### ISSUE TITLE
Invalid_argument: Notty: control char ... While trying to render the UI

### ISSUE THREAD

**Issue by infinity0** [hannesm/jackline#151]
~~~~
(Invalid_argument
  "Notty: control char: 0x09 (from: XX:XX:XX <-- XXXXXXXXX \t  \t\t\t\t \t \t \t    \t\t  \t   \t\t  \t\t)")
While trying to render the UI.  Try to scroll to another buddy (Page Up/Down), switch rendering of buddy list (F12), or clear this buddies messages (/clear<ret>); please report this bug (including the offending characters
and the error message)
~~~~

**Comment by hannesm** [comment]
which jackline version do you run?  and you know which client is on the other end?  looks like an otr whitespace tag to start a kex, but too tired to find out whether it is a correct sequence

**Comment by hannesm** [comment]
groupchat message or a private one?

**Comment by infinity0** [comment]
oh sorry, should have given more context. I'm on commit bf7d4ea. indeed i was trying to have an otr conversation with a special friend of mine who likes to write his own chat protocols and clients... will talk to him soon and figure out exactly which client this was.

**Comment by hannesm** [comment]
a similar issue occured to someone else: the message in that case was from the server administrator (and thus from `@foo.com`), it seems there's a path through xmpp_callbacks/cli_commands which does not (properly) handle otr messages (and/or doesn't strip the whitespace and tab characters), the message in question was: 0x09 in `MUC. \t  \t\t\t\t \t \t \t    \t\t  \t   \t\t  \t\t`

**Comment by hannesm** [comment]
I think I went through all possible code paths between xmpp input and ui.. and all are guarding control characters well, please let me know if you encounter this issue again (and if reproducible, please use debug mode (`-d true`) and send the offending XML stanza). thanks!
