### ISSUE TITLE
Allow join to be passed full JID

### ISSUE THREAD

**Issue by Ppjet6** [hannesm/jackline#154]
Handy to set a nick when joining a MUC

**Comment by hannesm** [comment]
we have atm `/join room@server`, you'd like to support `join room@server/my-nick`, or do I misunderstand you?

**Comment by Ppjet6** [comment]
On 2017/01/28, Hannes Mehnert wrote:
> we have atm `/join room@server`, you'd like to support `join room@server/my-nick`, or do I misunderstand you?

That's it

-- 
Maxime Buquet
