### ISSUE TITLE
Exception while trying to render the UI: Notty: control char: 0x0d

### ISSUE THREAD

**Issue by Engil** [hannesm/jackline#157]
Hello,

I stumbled upon this problem after joining a room with a title that seems to contain a few "\r\n".
It seems that the control char aren't escaped in the room title (should they be?) and that Notty just throw the exception as a result.

Haven't submitted a patch since I don't know if escaping is the right thing to do (and how), but the quickfix for me is just to remove those pesky \r\n altogether. :)

**Comment by hannesm** [comment]
Thanks for the report!

I'd recommend to use `Utils.validate_utf8 : string -> string` which gets rid of characters we don't want to display (replacing with `0xFFFD`).

This will leave newline characters in place, thus either they've to be stripped, or the rendering engine needs to split on newline and do sth sensible (it does [something magic](https://github.com/hannesm/jackline/blob/e5b3f702ec9af833022ddb5dee1d467980dda460/cli/cli_client.ml#L183-L195) for presence status, which may be factored out into a function and reused for topic/title).  The advantage of doing it on the rendering site is that we can adjust this at a later point, and keep the data as original as possible (in case it is written to disk) ;)

**Comment by Engil** [comment]
Thank you for your reply :)
I tried to patch it, but it seems that validate_utf8 isn't exactly the behaviour we want, see:
https://github.com/hannesm/jackline/blob/master/src/utils.ml#L34
`\r` is indeed stripped, but `\n` enter this match case which seems to add it back if I'm not mistaking

**Comment by hannesm** [comment]
could you try my `#fix-157` branch, pls?

**Comment by Engil** [comment]
I forgot to mention that I noticed the error came from `Muc.oneline`, moving this fix to this function should do the trick (the error is coming from the buddylist, where room descriptions are expanded)

**Comment by hannesm** [comment]
pushed 1f8f499

**Comment by Engil** [comment]
Works perfectly ! Thank you very much :)

**Comment by hannesm** [comment]
squash-merged to master. thanks!
