### ISSUE TITLE
/connect freezes jackline if there is no internet connection

### ISSUE THREAD

**Issue by sternenseemann** [hannesm/jackline#160]
It takes like half a minute until it fails because jackline can't resolve the host name. In this period jackline is unresponsive.

Reproduce like this:

1. Use DNS for connecting to the XMPP server
2. Have no working internet / 100% packet loss to the XMPP server
3. Start jackline and type `  /connect`

**Comment by hannesm** [comment]
yeah, DNS resolving is done synchronously/blocking at the moment (using `Unix.getaddrinfo`).

**Comment by hannesm** [comment]
sorry that it took me so long, but I finally managed to fix this issue (with not the most beautiful code atm)... please report back if this is fixed for you as well (or reopen if it is still an issue).  thanks!
