### ISSUE TITLE
/fingerprint: prevent running command on your own fingerprint

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#168]
It should not be possible to accidentally run `/fingerprint [my own fp]`.
We could also consider coloring the fp when running `/fingerprint` to query the status so that untrusted fingerprints are showed as `their otr fingerprint: [color]xxxxxx yyyyyy ...` where color is red/(yellow|green) and your own fingerprint in green.

We could also consider restricting /fingerprint in a session to being the FP currently used, and issue an error message otherwise (when would you want to add a fingerprint for a person that you currently have a OTR session with that is using a different key?)

**Comment by cfcs** [comment]
I think the coloring stuff would be nice, but I implemented the "reject own fp" in commit referenced above

**Comment by hannesm** [comment]
initially, only the (currently) active fingerprint for this session was accepted (see 4bc00cc9a51cefaa7914337a53fa18bb0d779b0c which modified this behaviour) -- should we revert to the old behaviour?

**Comment by cfcs** [comment]
I think it's nice to be able to load fingerprints off a napkin or similar before seeing the person online, but maybe the old behavior is better, I don't know. I think this (rejecting your own) should be done no matter what (it follows as a consequence of the old behavior, of course).

Do you remember why it was changed?
