### ISSUE TITLE
Provide option to place log window on top

### ISSUE THREAD

**Issue by duckdalbe** [hannesm/jackline#170]
I'd like to configure jackline so that  the log window is shown on top, above the contact list and chat window.

This doesn't need to be changeable at runtime, I guess.

**Comment by hannesm** [comment]
sorry for taking so long, but i just implemented it.  in your `~/.config/ocaml-xmpp-client/config.sexp`, you have to add `(log_top true)` (e.g. near to the end, before the final closing `)` -- after doing an `opam reinstall jackline`.  hope it is how you wanted it :)

**Comment by duckdalbe** [comment]
Works well, thank you!
