### ISSUE TITLE
no echo after quitting jackline in macOS

### ISSUE THREAD

**Issue by Iix** [hannesm/jackline#188]
In relation to bug #186 after quitting jackline in macOS terminal, there is no echo on key entries until the terminal is reset.

**Comment by hannesm** [comment]
maybe related to https://github.com/pqwy/notty/issues/22 which includes a workaround

**Comment by hannesm** [comment]
does `opam pin add jackline https://github.com/hannesm/jackline.git#reset-tc` work more nicely with your terminal?  this branch saves the terminal state and restores before exiting.

**Comment by hannesm** [comment]
the mentioned branch isn't worth it... but I've seen/heard about this very same issue on other platforms as well (using xterm and UNIX)... worth investigating further (but I can't reproduce yet)

**Comment by cfcs** [comment]
I posted a fix to the notty issue referenced by @hannesm above.

**Comment by cfcs** [comment]
Fixed in https://github.com/hannesm/jackline/commit/e9cc0a3cdd44f96065c91f5db826c9a504d11082#diff-1f947de1e211dae385d88d792a4fd397R29 here.

**Comment by hannesm** [comment]
fixed in notty 0.2.2
