### ISSUE TITLE
Link to aspcud is 404

### ISSUE THREAD

**Issue by bowlofeggs** [hannesm/jackline#194]
The [link to aspcud](http://www.cs.uni-potsdam.de/wv/aspcud/) in [README.md](https://github.com/hannesm/jackline/blob/bc36b1c8b80fee6baba4f91011cd01b82a06e8eb/README.md) is missing and the server responds with HTTP 404.

**Comment by cfcs** [comment]
This link https://www.cs.uni-potsdam.de/wv/software/ still has contact info for Torsten in case someone wants to write him and ask where it went.

**Comment by hannesm** [comment]
thanks for your report. now that opam2 landed, the instructions should be updated. opam2 also ships with a solver, so there's no longer a dependency to aspcud. sorry, I'm short on time this week, but will try to find some to update the instructions.

**Comment by bowlofeggs** [comment]
Ah ok. Well just for the record, I did get in touch with Torsten and he said the new link is https://github.com/potassco/aspcud.

**Comment by hannesm** [comment]
we're in opam2 world now, so aspcud is no longer a dependency :)
