### ISSUE TITLE
.ocamlinit for development environment no longer works

### ISSUE THREAD

**Issue by sternenseemann** [hannesm/jackline#215]
Error message currently is:

```
No such package: nocrypto
Cannot find file xmpp_client.cmo.
Cannot find file xmpp_client_cli.cmo.
```

I tried to update the library list and change to `cli_client.cmo`, but this would require loading `user.cmo` and `xjid.cmo` which aren't build by `pkg.ml` for some reason. I could only figure out how to build them manually using `ocamlbuild`.

**Comment by hannesm** [comment]
thanks for your report, in #216 I removed the `ocamlinit` file. In the future, it may be a good idea to use `dune` as build system which provides a `dune utop` subcommand that gets the load sequence right (most of the time at least).
