### ISSUE TITLE
IPv6 address support

### ISSUE THREAD

**Issue by sternenseemann** [hannesm/jackline#218]
Not sure if `jackline` uses ipv6 in address resolution, but if you enter an IPv6 address directly in `config.sexp`, an `EAFNOSUPPORT` error is generated.

**Comment by hannesm** [comment]
thanks for opening this issue, I implemented IPv6 support as a PR #220. Could you try this out, whether it works for you? I tested it behind a Deutsche Telekom IPv6 DSL on jabber.ccc.de successfully.

**Comment by hannesm** [comment]
in addition to "hard-coded IPv6 addresses", #220 also resolves the v6 addresses of hostnames and attempts to connect to these (with a slight preference for IPv6) -- it should work with v4-only and v6-only and dual-stack hosts.

**Comment by sternenseemann** [comment]
#220 works fine for me also (1und1). I tested the following things:

* Hard coded IPv4
* Hard coded IPv6
* DNS entry for `jabber.systemli.org` → resolves to IPv6

**Comment by hannesm** [comment]
thanks for your testing, I needed to revise #220 since it did not handle a connection well where the server supports IPv6 (has an AAAA record in DNS), but the client does not have an IPv6 address configured. this works now.

**Comment by hannesm** [comment]
(would be nice if you could check whether c6e3c5b works fine for you as well.

**Comment by sternenseemann** [comment]
I tested c6e3c5b110b395950f21554690d2ac3920e45ce2 and all cases above work as they should! I also tried removing my IPv6 address and connecting via DNS and in that case jackline picks the IPv4 address correctly.

**Comment by hannesm** [comment]
I just merged #220, closing this issue since IPv6 is supported in jackline now
