### ISSUE TITLE
Patch: F9: "copy-paste" mode

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#27]
For copying pastes from other users,
* toggles buddy list
* turns off message formatting (timestamps + line wrapping)
* hides own/local messages so your own messages don't interfere with the the selection
https://github.com/cfcs/jackline/commit/2dcf74bc5536fdc267ca7c72afc0c59165c06e73

**Comment by hannesm** [comment]
that's done now - slightly differently -- 8b743dcded7a07fcd4f4cb943bc1f465c0c3ee65 a4f4ede4f004e8bf7232301bcc814908cda7b4c5 and d5c40116ff894d057f7994413eaec5989869cd5f
