### ISSUE TITLE
Stop Ctrl-D from terminating session

### ISSUE THREAD

**Issue by andreas23** [hannesm/jackline#32]
Accidentally hitting Ctrl-D will terminate the jackline session immediately, taking away unread messages with it.

**Comment by hannesm** [comment]
i actually like the ctrl-d behaviour... use it all the time, and works as other command line tools..
but that could very well be customized with a lambda-term-inputrc https://github.com/diml/lambda-term/blob/c29990c5440b2d96191ffa56c0faa16d52c81ef1/man/lambda-term-inputrc.5

**Comment by andreas23** [comment]
Fair enough. In this case, please put the above link into the README. :)

**Comment by hannesm** [comment]
well, no clue what to put there tbh and whether it is respected/loaded... needs some investigation

**Comment by hannesm** [comment]
it is at least loaded (https://github.com/hannesm/jackline/blob/master/cli/jackline.ml#L5) -- missing here: documenting how to do custom key bindings in README

**Comment by cfcs** [comment]
As per hannes' link above, this can be achieved by creating a `~/.lambda-term-inputrc` file containing this option:
```
[read-line]
C-d: goto-eot
```

**Comment by hannesm** [comment]
thanks @cfcs, I now added this to the FAQ (in README.md).
