### ISSUE TITLE
Ability to supply separate jabber domain and TCP connection details

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#41]
It would be useful to be able to provide the TCP IP/port pair separate from the jabber domain, for use with proxies and multi-homed servers. Right now the hostname from the jabber id is used, which makes it a pain to connect through SSH-forwarded ports and the like.

**Comment by hannesm** [comment]
yo, PR welcome. related to #10...

**Comment by hannesm** [comment]
is now supported!
