### ISSUE TITLE
Request/receive, and send, message receipts

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#49]
It would be useful to have message receipts in jackline.

- http://stackoverflow.com/questions/20630926/how-to-get-acknowledgment-for-send-receive-message-in-ejabbered-xmpp
- http://xmpp.org/extensions/xep-0184.html

**Comment by hannesm** [comment]
oh yes, I so want to have this (see #25, most likely outdated)

**Comment by cfcs** [comment]
It seems like there are several XEPs that could be of relevance:
- http://xmpp.org/extensions/xep-0198.html `- Stream Management`
- http://xmpp.org/extensions/xep-0313.html `- Message Archive Management`
- http://xmpp.org/extensions/xep-0079.html `- Advanced Message Processing`
- http://xmpp.org/extensions/xep-0203.html `- Delayed Delivery`

**Comment by cfcs** [comment]
In relation to the latter (`XEP-0203: Delayed Delivery`) it would also be nice to have the original timestamp displayed for messages that are received upon reconnection, instead of displaying the local 'received' timestamp, since that's a bit misleading. I can't seem to find the relevant XEP right now. Thoughts?

**Comment by hannesm** [comment]
delayed delivery: see #31 which has a partial solution...

**Comment by hannesm** [comment]
closing since 184 is implemented now
