### ISSUE TITLE
Inconsistent status messages / silent error messages?

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#51]
I relatively often run into situations like this:
```
10 03:13:37 ***OTR*** encrypted connection established (ssid [xxFFxxFF] FFffFFff)
10 03:13:37 ***OTR key*** unverified key (used 20 times). please verify /fingerprint [fp] over second channel
10 03:13:37 ***OTR Warning*** didn't sent message, there was no encrypted connection: hey
```

It seems a bit counter-intuitive, does anyone have an idea what might be going?

**Comment by hannesm** [comment]
this is handling of multiple sessions with same status and priority... needs to be handled properly in UI

**Comment by hannesm** [comment]
plz reopen if still the case now that #73 is merged
