### ISSUE TITLE
reset notification.state when terminal is activated/focussed

### ISSUE THREAD

**Issue by hannesm** [hannesm/jackline#57]
currently `clear` is only done when the user moves the cursor in the buddy list (activating contact). would be fancy if it is cleared when the active contact is the only one with awaiting notifications and the window/terminal gets activated. but couldn't find an API/callback registration for this.

**Comment by cfcs** [comment]
Had a chance to look at this?

https://github.com/hannesm/jackline/pull/58

**Comment by hannesm** [comment]
now solving this using a `urgency hint` inside of the `notification_callback` shell script
