### ISSUE TITLE
Strip stupid libpurple HTML tags

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#7]
Consider automatically stripping '<FONT>' from the beginning of messages and '</FONT>' from the end of messages so we don't have to look at libpurple's HTML crap.
Perhaps this should be left in -- so users can tell people to stop using libpurple?

**Comment by cfcs** [comment]
Another annoying issue is that "<3" (very commonly used with my conversation partners for some reason!) gets shown as &lt;3, and, worse, don't show up in clients that do HTML parsing of messages.
Not sure what the best course of action is. Perhaps a configuration entry for each contact to do HTML encoding/decoding?

**Comment by hannesm** [comment]
@cfcs the issue of receiving `;3` has been solved in https://github.com/hannesm/xml/commit/4cc941e0dfa1082ebbc86e195bd17bf1ada8b013 , which I now included in `xmpp-opam` repository... thus, `opam update` followed by `opam upgrade` should fix this (this is only for clear-text message so far, encrypted messages are still broken (`<FONT>` and `&lt;3`))

**Comment by hannesm** [comment]
now fixed with https://github.com/hannesm/jackline/commit/49f01a76f9245955d8bcf306b150244daa3de62c @cfcs @policecar

**Comment by policecar** [comment]
\o/

Thank you!

Even tho i think those other clients shouldn't be sending html in the first place.

priska

**Comment by hannesm** [comment]
I thought so as well, but then [gajim-otr](https://github.com/wilhelmy/gajim-otr/blob/master/src/gotr/otrmodule.py#L626) and [mcabber](http://mcabber.com/hg/index.cgi/file/11a6318f30ad/mcabber/mcabber/otr.c#l620) ([calling into nohtml.c](http://mcabber.com/hg/index.cgi/file/11a6318f30ad/mcabber/mcabber/nohtml.c#l90), and also [remove tags and unescape](http://mcabber.com/hg/index.cgi/file/11a6318f30ad/mcabber/mcabber/nohtml.c#l39) (gajim [as well](https://github.com/wilhelmy/gajim-otr/blob/master/src/gotr/otrmodule.py#L600-L601)), next to libpurple (no, I didn't look deeper into their source) were convincing enough to just implement the same behaviour..

**Comment by cfcs** [comment]
Thanks!

**Comment by policecar** [comment]
Thank you!!

( and paula for mentioning it to you )
