### ISSUE TITLE
notifications on active contact

### ISSUE THREAD

**Issue by posiputt** [hannesm/jackline#79]
when a message from an active contact is received, the status in notification.state isn't updated to "connected_notifications" but stays at "connected". this is somewhat impractical if trying to build some kind of taskbar/systray icon that reads notification.state.
so jackline obviously doesn't have any way to determine if I am looking. would it be possible (and useful) to update notification.state when an active contact sends a message and then let jackline wait for some kind of acknowledgement, like pressing 'return' (or teh anykey!) before changing notification.state again to just 'connected'?

**Comment by hannesm** [comment]
yep... this is some regression, and connected with my attempts to fix #74

**Comment by hannesm** [comment]
looks like there's some regression regarding this issue again... sorry

**Comment by hannesm** [comment]
hmm, not really... there's a notification when talking to a@b -- focus on the window and unfocus again, next messages don't trigger an urgency thingy... likely related to xterm and i3.. (systray notification scripts shouldn't suffer from this)
