### ISSUE TITLE
Call the notification executable only on actual Jabber Messages

### ISSUE THREAD

**Issue by lukasepple** [hannesm/jackline#89]
Currently it also gets called if anything appears in the feed of my own jabber id, e. g. changing statuses, authorization requests, jackline startup message(s) etc.

This is pretty confusing to me.

**Comment by lukasepple** [comment]
If you could give me some hints I could try to look into this myself.

**Comment by hannesm** [comment]
the callout is [here](https://github.com/hannesm/jackline/blob/master/cli/cli_state.ml#L75), which is triggered by [any event](https://github.com/hannesm/jackline/blob/master/cli/cli_state.ml#L79-L97) (via a [mailbox var](http://ocsigen.org/lwt/2.5.0/api/Lwt_mvar)) (`git grep state_mvar` shows all the producers of events, mainly `notify` in `cli/cli_state.ml`, which is called in `cli/cli_commands.ml` by various callbacks form `src/xmpp_callbacks`).

I actually think that authorization requests are worth notifying.. not sure about the reconnects and other messages... if someone changes a status, there shouldn't be a notification (I also filter in my shell script for `if [ $2 != "connected" ]; then alarm me; fi`)

**Comment by lukasepple** [comment]
Mhhh but if you pass the script the event type as argument, I'd say that is rather a feature™ because there's a wider range of possibilities.

**Comment by hannesm** [comment]
while `$2` could be more fine-grained, I'm closing this for now... someone should write a proposal (in form of documentation and a PR) what `$2` can be

**Comment by lukasepple** [comment]
+1
