### ISSUE TITLE
Add timestamp to otr key display in `/otr info`?

### ISSUE THREAD

**Issue by cfcs** [hannesm/jackline#91]
`/otr info` currently produces output like this:
```
12:34:56 ***   unverified xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx xxxxxxxx (used in 99 sessions, resources: phone)
12:34:56 ***   unverified AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA AAAAAAAA (used in 5 sessions, resources: newphone)
```
I think it would be nice to add a `first seen: 1/4-1970` field to these messages to display to the user which one was the first to be encountered.

What do you think about that idea?

It would mean storing the time of contact. I'd be fine with rounding it to - well - the month, for example, to disclose less information in the unfortunate event of configuration file compromise.

**Comment by hannesm** [comment]
first seen and maybe last seen as well?

**Comment by cfcs** [comment]
Hmm, yes, I guess that could be useful too, to determine if a key doesn't seem to be in use anymore.
