### ISSUE TITLE
' breaks OTR encryption

### ISSUE THREAD

**Issue by lukasepple** [hannesm/jackline#96]
Reproduce: send a single `'` (Ascii `0x27`) from jackline. Other Clients will receive a `?OTR:…` message. Probably a Encoding related issue.

Tested between Gajim and jackline.

**Comment by lukasepple** [comment]
Possibly a Gajim issue

**Comment by hannesm** [comment]
yes, this is gajim's fault (also happens if you use mcabber on the other side, and type in `'`)... problem is likely somewhere around https://github.com/python-otr/gajim-otr/blob/master/src/gotr/otrmodule.py#L600-L604 (but I decided to not investigate any further)
